/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csc4380.alewis91;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Toolkit;

/**
 *
 * @author alewis91
 */
public class MainFrame_Assignment4_alewis91 extends javax.swing.JFrame {

    /**
     * Creates new form Assignment4
     */
    DrawingPanel_Assignment4_alewis91 dPanel;
    public MainFrame_Assignment4_alewis91() {
        
        initComponents();
        setTitle("Assignment 4 - alewis91");
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((screen.getWidth() - getWidth()) /2);
        int y = (int) ((screen.getHeight() -getHeight()) /2);
        setLocation(x, y); 
        dPanel  = new DrawingPanel_Assignment4_alewis91();
        dPanel.setSize(this.getWidth()-100, this.getHeight()-100);
        this.add(dPanel);
        //dPanel.setBackground(Color.RED);
        
        
        
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        txtXRec = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        txtYRec = new javax.swing.JTextField();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        btnRec = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 0), new java.awt.Dimension(150, 0), new java.awt.Dimension(50, 32767));
        txtXCirc = new javax.swing.JTextField();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        txtYCirc = new javax.swing.JTextField();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        btnCirc = new javax.swing.JButton();
        MenuBar = new javax.swing.JMenuBar();
        btnExit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        jToolBar1.setRollover(true);

        txtXRec.setText("0");
        txtXRec.setToolTipText("X1");
        txtXRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtXRecActionPerformed(evt);
            }
        });
        jToolBar1.add(txtXRec);
        jToolBar1.add(filler1);

        txtYRec.setText("0");
        txtYRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtYRecActionPerformed(evt);
            }
        });
        jToolBar1.add(txtYRec);
        jToolBar1.add(filler2);

        btnRec.setText("Draw Rectangle");
        jToolBar1.add(btnRec);
        jToolBar1.add(filler3);

        txtXCirc.setText("0");
        jToolBar1.add(txtXCirc);
        jToolBar1.add(filler4);

        txtYCirc.setText("0");
        jToolBar1.add(txtYCirc);
        jToolBar1.add(filler5);

        btnCirc.setText("Draw Circle");
        jToolBar1.add(btnCirc);

        btnExit.setText("Exit");
        MenuBar.add(btnExit);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(356, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        this.dPanel.setSize(this.getWidth(), this.getHeight()); 
    }//GEN-LAST:event_formComponentResized

    private void txtXRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtXRecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtXRecActionPerformed

    private void txtYRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtYRecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtYRecActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame_Assignment4_alewis91.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame_Assignment4_alewis91.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame_Assignment4_alewis91.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame_Assignment4_alewis91.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame_Assignment4_alewis91().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JButton btnCirc;
    private javax.swing.JMenu btnExit;
    private javax.swing.JButton btnRec;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField txtXCirc;
    private javax.swing.JTextField txtXRec;
    private javax.swing.JTextField txtYCirc;
    private javax.swing.JTextField txtYRec;
    // End of variables declaration//GEN-END:variables
}
